"use client";

import { useEffect, useMemo, useState } from "react";
import { MagnifyingGlass, PencilSimple, Plus, Tag, Trash, X } from "@phosphor-icons/react";
import { useMasterDataStore } from "@/stores/master-data-store";
import { MasterDataNotice } from "@/components/settings/master-data-notice";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";

export default function MasterCategoriesPage() {
  const { categories, categoryItems, loadCategories, addCategory, updateCategory, removeCategory, isLoading, isSaving, error } = useMasterDataStore();
  const [query, setQuery] = useState("");
  const [open, setOpen] = useState(false);
  const [editingIndex, setEditingIndex] = useState<number | null>(null);
  const [name, setName] = useState("");
  useEffect(() => { void loadCategories(); }, [loadCategories]);
  const filtered = useMemo(() => categoryItems.filter((item) => item.name.toLowerCase().includes(query.toLowerCase())), [categoryItems, query]);
  const openCreate = () => { setEditingIndex(null); setName(""); setOpen(true); };
  const openEdit = (id: string, value: string) => { setEditingIndex(categoryItems.findIndex((item) => item.id === id)); setName(value); setOpen(true); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); const ok = editingIndex === null ? await addCategory(name) : await updateCategory(editingIndex, name); if (ok) setOpen(false); };
  return <div className="space-y-6">
    <MasterDataNotice isLoading={isLoading} error={error} />
    <div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2.5"><h2 className="text-2xl font-bold tracking-tight">Project Categories</h2><span className="rounded-md bg-muted/60 px-2 py-0.5 text-xs font-semibold text-muted-foreground">{filtered.length} categories</span></div><p className="mt-1 text-xs text-muted-foreground">Categories available in every project form and filter.</p></div><button onClick={openCreate} className="flex items-center gap-1.5 rounded-lg bg-primary px-3.5 py-2 text-xs font-semibold text-primary-foreground"><Plus size={14} weight="bold" /> Add category</button></div>
    <div className="flex items-center rounded-lg border border-border/60 bg-card p-2.5"><div className="relative w-full max-w-sm"><MagnifyingGlass size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search categories" className="w-full rounded-lg border border-border bg-card py-1.5 pl-9 pr-8 text-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" />{query && <button onClick={() => setQuery("")} className="absolute right-2.5 top-1/2 -translate-y-1/2 text-muted-foreground"><X size={13} /></button>}</div></div>
    <div className="overflow-hidden rounded-lg border border-border/60 bg-card"><table className="w-full text-left text-xs"><thead><tr className="border-b border-border/60 bg-muted/40 text-[11px] font-bold uppercase tracking-wider text-muted-foreground"><th className="px-5 py-3">Category</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-border/50">{filtered.length === 0 && !isLoading ? <tr><td colSpan={2} className="py-12 text-center text-muted-foreground">No categories found.</td></tr> : filtered.map((item) => <tr key={item.id} className="hover:bg-muted/20"><td className="px-5 py-3.5"><div className="flex items-center gap-2.5"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary"><Tag size={15} /></span><span className="font-semibold">{item.name}</span>{item.isDefault && <span className="rounded-full bg-muted px-2 py-0.5 text-[10px] text-muted-foreground">Default</span>}</div></td><td className="px-5 py-3.5 text-right"><button onClick={() => openEdit(item.id, item.name)} className="rounded-md p-1.5 text-muted-foreground hover:bg-primary/10 hover:text-primary"><PencilSimple size={14} /></button><button onClick={() => void removeCategory(item.name)} className="rounded-md p-1.5 text-muted-foreground hover:bg-rose-500/10 hover:text-rose-600"><Trash size={14} /></button></td></tr>)}</tbody></table></div>
    <Sheet open={open} onOpenChange={setOpen}><SheetContent side="right" className="flex h-full w-full flex-col border-l border-border bg-card p-0 shadow-none sm:max-w-md"><form onSubmit={save} className="flex h-full flex-col"><div className="border-b border-border/60 px-6 py-5"><SheetHeader><SheetTitle className="text-lg font-bold">{editingIndex === null ? "Add category" : "Edit category"}</SheetTitle><SheetDescription className="text-xs">This value will be available across all project forms.</SheetDescription></SheetHeader></div><div className="flex-1 p-6"><div className="space-y-1.5"><label className="text-xs font-semibold">Category name</label><input value={name} onChange={(event) => setName(event.target.value)} required autoFocus className="h-10 w-full rounded-lg border border-border bg-background px-3 text-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" /></div></div><div className="flex justify-end gap-2.5 border-t border-border/60 bg-muted/20 px-6 py-4"><button type="button" onClick={() => setOpen(false)} className="h-9 rounded-lg border border-border px-4 text-xs font-semibold text-muted-foreground">Cancel</button><button type="submit" disabled={isSaving || !name.trim()} className="h-9 rounded-lg bg-primary px-5 text-xs font-semibold text-primary-foreground disabled:opacity-50">Save category</button></div></form></SheetContent></Sheet>
  </div>;
}
