"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { MagnifyingGlass, PencilSimple, Plus, Trash, UsersThree, X } from "@phosphor-icons/react";
import { apiFetch } from "@/lib/api-client";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import type { User } from "@/types";

export default function UsersPage() {
  const [users, setUsers] = useState<User[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<User | null>(null);
  const [currentRole, setCurrentRole] = useState("admin");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [role, setRole] = useState("user"); const [status, setStatus] = useState("active");
  const load = useCallback(async () => { setLoading(true); try { const res = await apiFetch("/api/users?limit=100"); const body = await res.json(); if (!res.ok) throw new Error(body.message); setUsers(body.data || []); } catch (error) { toast.error(error instanceof Error ? error.message : "Failed to load users"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); void apiFetch("/api/auth/me").then((res) => res.json()).then((body) => setCurrentRole(body.data?.role || "admin")); }, [load]);
  const filtered = useMemo(() => users.filter((user) => `${user.name} ${user.email} ${user.role}`.toLowerCase().includes(query.toLowerCase())), [users, query]);
  const create = () => { setEditing(null); setName(""); setEmail(""); setPassword(""); setRole("user"); setStatus("active"); setOpen(true); };
  const edit = (user: User) => { setEditing(user); setName(user.name); setEmail(user.email); setPassword(""); setRole(user.role || "user"); setStatus(user.accountStatus || "active"); setOpen(true); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { const payload: Record<string, unknown> = { name, email, role, accountStatus: status }; if (password) payload.password = password; const res = await apiFetch(editing ? `/api/users/${editing.id}` : "/api/users", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await res.json(); if (!res.ok) throw new Error(body.message); toast.success(editing ? "User updated successfully" : "User created successfully"); setOpen(false); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Failed to save user"); } finally { setSaving(false); } };
  const remove = async (user: User) => { if (!confirm(`Move ${user.name} to trash?`)) return; const res = await apiFetch(`/api/users/${user.id}`, { method: "DELETE" }); const body = await res.json(); if (!res.ok) return toast.error(body.message || "Failed to delete user"); toast.success("User moved to trash"); await load(); };
  const forceLogout = async () => { if (!editing || !confirm(`Sign ${editing.name} out on all devices?`)) return; const res = await apiFetch(`/api/users/${editing.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ forceLogout: true }) }); const body = await res.json(); if (!res.ok) return toast.error(body.message || "Failed to sign user out"); toast.success("All user sessions were revoked"); };
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2.5"><h2 className="text-2xl font-bold tracking-tight">User management</h2><span className="rounded-md bg-muted/60 px-2 py-0.5 text-xs font-semibold text-muted-foreground">{users.length} users</span></div><p className="mt-1 text-xs text-muted-foreground">Manage accounts, roles, access status, and passwords.</p></div><button onClick={create} className="flex items-center gap-1.5 rounded-lg bg-primary px-3.5 py-2 text-xs font-semibold text-primary-foreground"><Plus size={14} weight="bold" /> Add user</button></div>
    <div className="rounded-lg border border-border/60 bg-card p-2.5"><div className="relative max-w-sm"><MagnifyingGlass size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search users" className="h-9 w-full rounded-lg border border-border bg-background pl-9 pr-8 text-xs outline-none focus:border-primary"/>{query && <button onClick={() => setQuery("")} className="absolute right-2.5 top-1/2 -translate-y-1/2 text-muted-foreground"><X size={13}/></button>}</div></div>
    <div className="overflow-x-auto rounded-lg border border-border/60 bg-card"><table className="w-full min-w-[720px] text-left text-xs"><thead><tr className="border-b border-border/60 bg-muted/40 text-[11px] font-bold uppercase tracking-wider text-muted-foreground"><th className="px-5 py-3">User</th><th className="px-5 py-3">Role</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Last login</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-border/50">{filtered.map((user) => <tr key={user.id} className="hover:bg-muted/20"><td className="px-5 py-3.5"><div className="flex items-center gap-2.5"><span className="grid h-8 w-8 place-items-center rounded-full bg-primary/10 font-bold text-primary">{user.name[0]?.toUpperCase()}</span><div><p className="font-semibold">{user.name}</p><p className="text-[11px] text-muted-foreground">{user.email}</p></div></div></td><td className="px-5 py-3.5 capitalize">{user.role}</td><td className="px-5 py-3.5"><span className={user.accountStatus === "suspended" ? "rounded-md bg-rose-500/10 px-2 py-1 font-semibold text-rose-600" : "rounded-md bg-primary/10 px-2 py-1 font-semibold text-primary"}>{user.accountStatus || "active"}</span></td><td className="px-5 py-3.5 text-muted-foreground">{user.lastLoginAt ? new Date(user.lastLoginAt).toLocaleString("en-US") : "Never"}</td><td className="px-5 py-3.5 text-right"><button onClick={() => edit(user)} className="rounded-md p-1.5 text-muted-foreground hover:bg-primary/10 hover:text-primary"><PencilSimple size={14}/></button><button onClick={() => void remove(user)} className="rounded-md p-1.5 text-muted-foreground hover:bg-rose-500/10 hover:text-rose-600"><Trash size={14}/></button></td></tr>)}{!loading && !filtered.length && <tr><td colSpan={5} className="py-12 text-center text-muted-foreground">No users found.</td></tr>}</tbody></table></div>
    <Sheet open={open} onOpenChange={setOpen}><SheetContent side="right" className="flex h-full w-full flex-col border-l border-border bg-card p-0 shadow-none sm:max-w-md"><form onSubmit={save} className="flex h-full flex-col"><div className="border-b border-border/60 px-6 py-5"><SheetHeader><SheetTitle>{editing ? "Edit user" : "Invite user"}</SheetTitle><SheetDescription>Configure account details and transactional access.</SheetDescription></SheetHeader></div><div className="flex-1 space-y-4 overflow-y-auto p-6"><Field label="Full name"><input required value={name} onChange={(e) => setName(e.target.value)} className="h-10 w-full rounded-lg border border-border bg-background px-3 text-xs"/></Field><Field label="Email address"><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="h-10 w-full rounded-lg border border-border bg-background px-3 text-xs"/></Field><Field label={editing ? "New password (optional)" : "Temporary password"}><input required={!editing} minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="h-10 w-full rounded-lg border border-border bg-background px-3 text-xs"/></Field>{currentRole === "superadmin" ? <Field label="Role"><Select value={role} onValueChange={setRole}><SelectTrigger className="h-10 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="user">User</SelectItem><SelectItem value="admin">Administrator</SelectItem><SelectItem value="superadmin">Super Administrator</SelectItem></SelectContent></Select></Field> : <div className="rounded-lg border border-border/60 bg-muted/20 p-3"><p className="text-xs font-semibold">Role: User</p><p className="mt-1 text-[11px] text-muted-foreground">Invited users receive transactional access only.</p></div>}<Field label="Account status"><Select value={status} onValueChange={setStatus}><SelectTrigger className="h-10 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="active">Active</SelectItem><SelectItem value="suspended">Suspended</SelectItem></SelectContent></Select></Field>{editing&&<div className="rounded-lg border border-border/60 bg-muted/20 p-3"><p className="text-xs font-semibold">Active sessions</p><p className="mt-1 text-[11px] text-muted-foreground">Immediately revoke this user&apos;s sessions on every device.</p><button type="button" onClick={()=>void forceLogout()} className="mt-3 rounded-lg border border-border bg-card px-3 py-2 text-xs font-semibold text-rose-600 hover:bg-rose-500/10">Force logout</button></div>}</div><div className="flex justify-end gap-2 border-t border-border/60 bg-muted/20 px-6 py-4"><button type="button" onClick={() => setOpen(false)} className="h-9 rounded-lg border border-border px-4 text-xs font-semibold">Cancel</button><button disabled={saving} className="h-9 rounded-lg bg-primary px-5 text-xs font-semibold text-primary-foreground">{saving ? "Saving..." : "Save user"}</button></div></form></SheetContent></Sheet>
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><label className="text-xs font-semibold">{label}</label>{children}</div>; }
