"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowClockwise, CaretDown, CaretUp, MagnifyingGlass, PencilSimple, Plus, Rows, Trash, X } from "@phosphor-icons/react";
import type { MasterSection } from "@/types";
import { usePrivilegesStore } from "@/stores/privileges-store";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Skeleton } from "@/components/ui/skeleton";

export default function MasterSectionsPage() {
  const { sections, menus, isLoading, loadAllPrivileges, addSection, updateSection, removeSection, reorderSections } = usePrivilegesStore();
  const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<MasterSection | null>(null); const [name, setName] = useState("");
  useEffect(() => { void loadAllPrivileges(); }, [loadAllPrivileges]);
  const filtered = useMemo(() => sections.filter((item) => item.name.toLowerCase().includes(query.toLowerCase())), [sections, query]);
  const showCreate = () => { setEditing(null); setName(""); setOpen(true); };
  const showEdit = (item: MasterSection) => { setEditing(item); setName(item.name); setOpen(true); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); const trimmed = name.trim(); if (!trimmed) return; const ok = editing ? await updateSection(editing.id, trimmed) : await addSection(trimmed); if (ok) setOpen(false); };
  const move = async (item: MasterSection, direction: "up" | "down") => { const index = sections.findIndex((section) => section.id === item.id); const target = direction === "up" ? index - 1 : index + 1; if (index < 0 || target < 0 || target >= sections.length) return; const copy = [...sections]; const [moved] = copy.splice(index, 1); copy.splice(target, 0, moved); await reorderSections(copy); };
  const remove = async (item: MasterSection) => { if (confirm(`Delete section "${item.name}"? Its menus will be moved to General.`)) await removeSection(item.id); };
  return <div className="space-y-6">
    <div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2.5"><h2 className="text-2xl font-bold tracking-tight">Navigation sections</h2><span className="rounded-md bg-muted/60 px-2 py-0.5 text-xs font-semibold text-muted-foreground">{filtered.length} sections</span></div><p className="mt-1 text-xs text-muted-foreground">Group sidebar menus under configurable headings.</p></div><div className="flex gap-2"><button onClick={showCreate} className="flex items-center gap-1.5 rounded-lg bg-primary px-3.5 py-2 text-xs font-semibold text-primary-foreground"><Plus size={14} weight="bold" /> Add section</button><button onClick={() => void loadAllPrivileges()} disabled={isLoading} className="flex items-center gap-1.5 rounded-lg border border-border bg-muted/60 px-3 py-2 text-xs font-semibold"><ArrowClockwise size={14} className={isLoading ? "animate-spin" : ""} /> Refresh</button></div></div>
    <div className="flex items-center rounded-lg border border-border/60 bg-card p-2.5"><div className="relative w-full max-w-sm"><MagnifyingGlass size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search sections" className="w-full rounded-lg border border-border bg-card py-1.5 pl-9 pr-8 text-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" />{query && <button onClick={() => setQuery("")} className="absolute right-2.5 top-1/2 -translate-y-1/2 text-muted-foreground"><X size={13} /></button>}</div></div>
    <div className="overflow-hidden rounded-lg border border-border/60 bg-card"><table className="w-full text-left text-xs"><thead><tr className="border-b border-border/60 bg-muted/40 text-[11px] font-bold uppercase tracking-wider text-muted-foreground"><th className="px-5 py-3">Section</th><th className="hidden px-5 py-3 sm:table-cell">Menus</th><th className="px-5 py-3 text-center">Order</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-border/50">{isLoading && !sections.length ? Array.from({ length: 4 }).map((_, index) => <tr key={index}><td className="px-5 py-3"><Skeleton className="h-5 w-32" /></td><td colSpan={3} /></tr>) : filtered.length === 0 ? <tr><td colSpan={4} className="py-12 text-center text-muted-foreground">No sections found.</td></tr> : filtered.map((item) => { const absoluteIndex = sections.findIndex((section) => section.id === item.id); const count = menus.filter((menu) => menu.section?.toLowerCase() === item.name.toLowerCase()).length; return <tr key={item.id} className="hover:bg-muted/20"><td className="px-5 py-3.5"><div className="flex items-center gap-2.5"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary"><Rows size={15} /></span><span className="font-semibold">{item.name}</span></div></td><td className="hidden px-5 py-3.5 text-muted-foreground sm:table-cell">{count} menus</td><td className="px-5 py-3.5"><div className="flex justify-center gap-1"><button disabled={absoluteIndex === 0} onClick={() => void move(item, "up")} className="rounded p-1 text-muted-foreground disabled:opacity-25"><CaretUp size={14} /></button><button disabled={absoluteIndex === sections.length - 1} onClick={() => void move(item, "down")} className="rounded p-1 text-muted-foreground disabled:opacity-25"><CaretDown size={14} /></button></div></td><td className="px-5 py-3.5 text-right"><button onClick={() => showEdit(item)} className="rounded-md p-1.5 text-muted-foreground hover:bg-primary/10 hover:text-primary"><PencilSimple size={14} /></button><button onClick={() => void remove(item)} className="rounded-md p-1.5 text-muted-foreground hover:bg-rose-500/10 hover:text-rose-600"><Trash size={14} /></button></td></tr>; })}</tbody></table></div>
    <Sheet open={open} onOpenChange={setOpen}><SheetContent side="right" className="flex h-full w-full flex-col border-l border-border bg-card p-0 shadow-none sm:max-w-md"><form onSubmit={save} className="flex h-full flex-col"><div className="border-b border-border/60 px-6 py-5"><SheetHeader><SheetTitle className="text-lg font-bold">{editing ? "Edit section" : "Add section"}</SheetTitle><SheetDescription className="text-xs">Section names are reflected directly in the sidebar.</SheetDescription></SheetHeader></div><div className="flex-1 p-6"><div className="space-y-1.5"><label className="text-xs font-semibold">Section name</label><input value={name} onChange={(event) => setName(event.target.value)} required autoFocus className="h-10 w-full rounded-lg border border-border bg-background px-3 text-xs outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" /></div></div><div className="flex justify-end gap-2.5 border-t border-border/60 bg-muted/20 px-6 py-4"><button type="button" onClick={() => setOpen(false)} className="h-9 rounded-lg border border-border px-4 text-xs font-semibold text-muted-foreground">Cancel</button><button type="submit" disabled={!name.trim()} className="h-9 rounded-lg bg-primary px-5 text-xs font-semibold text-primary-foreground disabled:opacity-50">Save section</button></div></form></SheetContent></Sheet>
  </div>;
}
